name: Maven Package upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - '!release-branch'
      - release*
      - master
      - 1.*
      - develop*
      - MOSIP*

jobs:
  build-dockers:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'mosip-file-server'
            SERVICE_NAME: 'mosip-file-server'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: syedsalman3753/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      BUILD_ARTIFACT: ${{ matrix.BUILD_ARTIFACT || false }}
      ONLY_DOCKER: ${{ matrix.ONLY_DOCKER || false }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}